version: '3.8'

services:
  aspnet-service:
    image: 192.168.10.182:5000/aspnet-swarm-test
    deploy:
      placement:
        constraints:
          - node.labels.type == aspnet

  fastapi-service:
    image: fastapi-swarm-test
    deploy:
      placement:
        constraints:
          - node.labels.type == fastapi

  nginx-service:
    image: 192.168.10.182:5000/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./main.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi-service
      - aspnet-service