version: '3.8'

services:
  aspnet-service:
    image: aspnet-swarm-test
    networks:
      - shared-net

  fastapi-service:
    image: fastapi-swarm-test
    networks:
      - shared-net
      
  nginx-service:
    image: nginx:latest
    networks:
      - shared-net
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-available/proxy:/etc/nginx/sites-available/proxy:ro
      - /etc/nginx/sites-enabled/proxy:/etc/nginx/sites-enabled/proxy:ro
    command: ["/bin/sh", "-c", "mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.bak &&  nginx -g 'daemon off;'"]
    depends_on:
      - fastapi-service
      - aspnet-service

networks:
  shared-net:
    external: true